server:
  port: 8011
rpc:
  provider:
    port: 20811
  application:
    name: provider-order

log-out:
  dir-name: myOrder

spring:
  datasource:
    url: jdbc:mysql://usher:3306/usher_order
    username: root
    password: Shang1996.
id:
  organization:
    # 机构代码
    code: 11
