server:
  port: 8002

rpc:
  metadata-report:
    address: nacos://cloud:8848
  registry:
    host: cloud
    port: 8848
  provider:
    port: 20802
  application:
    name: provider-user

log-out:
  dir-name: user
spring:
  datasource:
    url: jdbc:mysql://cloud:3306/usher_user?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    ignore:
      tables: sys_dept_menu,sys_dept_power,sys_role_dept

redis:
  normal:
    ip: cloud
    port: 6379
    password: uhyils
  hotspot:
    hosts: prod:26380;prod:26381;prod:26382
    password: uhyils
    sentinels: mymaster


rabbit:
  host: cloud
  port: 5672
  username: admin
  password: admin

id:
  organization:
    # 机构代码
    code: 10

dynamic:
  mark: dy_user
