server:
  port: 8002

rpc:
  metadata-report:
    address: nacos://cloud:8848
  registry:
    host: cloud
    port: 8848
  provider:
    port: 20802
  application:
    name: provider-user

log-out:
  dir-name: user
spring:
  datasource:
    url: jdbc:mysql://cloud:3306/usher_user?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: Shang1996.
    ignore:
      tables: sys_dept_menu,sys_dept_power,sys_role_dept

redis:
  normal:
    ip: cloud
    port: 6379
    password: uhyils
  hotspot:
    hosts: ${hosts}:26380;${hosts}:26381;${hosts}:26382
    password: uhyils
    sentinels: mymaster

id:
  organization:
    # 机构代码
    code: 10

dynamic:
  mark: dy_user
rocketmq:
  config:
    producerName: user_group
